### ISSUE TITLE
Vector2IO and Vector3IO use different patterns

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#100]
I ran into this in Natural Selection, which uses both Vector2 and Vector3.

Vector2IO and Vector3IO are currently implemented differently, using different patterns. 

As the result of https://github.com/phetsims/dot/issues/76, Vector2IO delegates to Vector2:

```js
  static toStateObject( vector2 ) {
    validate( vector2, this.validator );
    return vector2.toStateObject();
  }

  static fromStateObject( stateObject ) {
    return Vector2.fromStateObject( stateObject );
  }
```

Vector3IO does not delegate to Vector3:

```js
  static toStateObject( vector3 ) {
    validate( vector3, this.validator );
    return { x: vector3.x, y: vector3.y, z: vector3.z };
  }

  static fromStateObject( stateObject ) {
    return new Vector3( stateObject.x, stateObject.y, stateObject.z );
  }
```

Unless there's a good reason not to,  recommended to use the same pattern (preferably delegation) in both IO types, to improve readability and comprehension.

**Comment by pixelzoom** [comment]
Done in the above commits.  No PhET-iO API changes were required. 

Would one of the assignees please volunteer to review?

**Comment by zepumph** [comment]
Changes look great thanks!
