### ISSUE TITLE
Eliminate Utils.isInteger

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#104]
Utils.isInteger was written to support IE since IE doesn't have `Number.isInteger`.  Now that we no longer support IE, we can eliminate `Utils.isInteger` and use `Number.isInteger`.

See also https://github.com/phetsims/tasks/issues/1037 and https://github.com/phetsims/tasks/issues/1039

**Comment by samreid** [comment]
Pushed and ready for review.  Most conversions were straightforward `Utils.isInteger=>Number.isInteger`, and in some cases removing the `Utils` import.  Dot had a different commit because it also removed the function, and updated documentation.  @arouinfar can you please request a reviewer?

**Comment by ariel-phet** [comment]
@chrisklus is on the case

**Comment by chrisklus** [comment]
Commits look good, updated docs/Utils look good, and I can't find any missed usages. Thanks @samreid, back to you.

**Comment by samreid** [comment]
Thanks for the review, closing.
