### ISSUE TITLE
suggestions for Bounds2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#106]
A couple of suggestions for Bounds2:

* Unlike `dilated` and `eroded`, `shifted` takes 2 args, and there is no `shiftedXY`. Ditto for `shift`.   I'm constantly guessing which calls to use and getting it wrong. Examples like this would be a lot clearer (and easier to write by guessing) if the APIs were the same for dialtion, erosion, and shifting:

```js
// I write this, which is wrong
someBounds.dilateXY( 100, 50 ).shiftXY( -100, -50 );

// This is correct, but inconsistent
someBounds.dilateXY( 100, 50 ).shift( -100, -50 );
```

* `dilated` and `dilatedXY` contain duplicated code.  `dilated` should be implemented by calling `dilatedXY`.  Ditto for `dilate`. Recommend to change to:

```js
  dilated( d ) {
    return this.dilatedXY( d, d );
  }

  dilate( d ) {
    return this.dilateXY( d, d );
  }
```

Assigning to @jonathanolson to weigh in.

**Comment by jonathanolson** [comment]
I believe I've handled the above, can you verify?

**Comment by pixelzoom** [comment]
👍🏻 closing.

**Comment by pixelzoom** [comment]
Reopening.  Should Bounds3 be addressed too? There is similar duplication and inconsistency in Bounds3.   And now Bounds2 and Bounds3 are have inconsisent APIs.

**Comment by jonathanolson** [comment]
Agreed, they should be handled. Good catch!

Handled above, closing.
