### ISSUE TITLE
Use a more accurate number library

### ISSUE THREAD

**Issue by zepumph** [phetsims/dot#116]
From https://github.com/phetsims/dot/issues/113 and many other times since moving to javascript, there are rounding problems with javascript's floating point implementation.

We have reached the point that it would be nice to investigate another library, and we feel like it is potentially possible to do so in specific cases, instead of needing to use this everywhere all at once. 

Marking as an epic.

**Comment by zepumph** [comment]
Some ideas about this over in https://github.com/phetsims/dot/issues/113 is to replace the ScientificNotationNode's usage of `toExponential`, and potentially to rewrite DOT/Utils.toFixed.

**Comment by kathy-phet** [comment]
Found a different solution. Closing, and will re-open if needed.
