### ISSUE TITLE
add Bounds2.closestBoundaryPointTo

### ISSUE THREAD

**Issue by zepumph** [phetsims/dot#119]
After speaking with @jonathanolson and @chrisklus about solving https://github.com/phetsims/number-compare/issues/30, this is the best path forward.

**Comment by zepumph** [comment]
@jonathanolson wanted to take one more look but had to leave. Please note that we needed some debugging from your last view of this.

**Comment by zepumph** [comment]
It was actually easier to do thing manually in https://github.com/phetsims/number-compare/issues/30, but we have unit tests still, and it was working in our sim for 4 hours until we removed it!

**Comment by jonathanolson** [comment]
Looks good to me!
