### ISSUE TITLE
create Dimension2IO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#123]
Dimension2IO us need in FEL, and does not exist yet.  To be patterned off of Vector2.Vector2IO.  

Dimension2 also needs to be converted to TypeScript.

**Comment by pixelzoom** [comment]
Lucky me again... Dimension2 needs to be converted to TypeScript.

**Comment by pixelzoom** [comment]
In the above commits, I converted Dimension2 to TypeScript, then implemented Dimension2IO using the same pattern as Vector2IO and RangeIO.

Dimension2IO is not used in FEL yet, but will be very soon. I tested by temporarily adding this to FEL Magnet.ts:

```ts
    const sizeProperty = new Property( new Dimension2( 0, 0 ), {
      tandem: options.tandem.createTandem( 'sizeProperty' ),
      phetioValueType: Dimension2.Dimension2IO
    } );
    sizeProperty.link( size => console.log( `size=${sizeProperty.value}` ) );
```

Then in Studio, I verified that I could get and set `faradaysElectromagneticLab.barMagnetScreen.model.barMagnet.sizeProperty`, and that it had type `PropertyIO<Dimension2IO>`.

@samreid or @zepumph care to do a quick review? Close if OK.

**Comment by zepumph** [comment]
* Do we need to support infinity here? I know we did for Bounds2. I am happy to keep it even if there are not current usages of inifinte `Dimension2` values. I kinda felt that that an infinite dimension goes beyond the scope of the class (in practice though not necessarily in theory). Do you have an opinion?
* I like the pattern of having a prototype `toStateObject` even though there are no usages of it yet. I think this pattern should extend to common-code, data-type IOType types, and should not be used by sim specific types, where most often you can just utilize the default toStateObject serialization from providing the stateSchema. Greenhouse does a good job of showing the simplicity of using the default serialization pattern. Does that sound good to you?
* Minor doc update committed above.

**Comment by pixelzoom** [comment]
> * Do we need to support infinity here? ...

I don't know.  But supporting infinity (initially) seemed safest.  Assigning to @jonathanolson to chime in -- should Dimension2IO support Infinity and -Infinity?

> * I like the pattern of having a prototype `toStateObject` ... Does that sound good to you?

Me too, and yes.   Improving the "how to" IOType documentation would also help. The current state of affairs is that developers create new IOTypes by copying and modifying an existing IOType.  And since there is no documented pattern for implementing IOTypes, the implementations are all over the place.   I prefer the pattern where the IOType delegates to the core type as much as possible (for `toStateObject`, `fromStateObject`, etc.)

> * Minor doc update committed above.

That doc was based on RangeIO, so I fixed that doc too in the above commit.

**Comment by jonathanolson** [comment]
I think it sounds safest to include support for infinite values. We might include "slices" of Bounds2 objects, and those could be empty.

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.  Since Dimension2 supports infinity, Dimension2IO must support it.  So no change needed to Dimension2IO.

Back to @zepumph in case he wants to create an issue related to "IOType patterns" as described in https://github.com/phetsims/dot/issues/123#issuecomment-1791284520.  Feel free to close when you're done.

**Comment by zepumph** [comment]
Right thanks. I added the patterns we discussed into the technical guide. Any other IOType patterns that you can think of for me to update?

**Comment by pixelzoom** [comment]
I can't think of anything else to update at the moment. So... closing.
