### ISSUE TITLE
Bounds2: cannot read property 'x' of null

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#26]
I've been seeing this error for about a week in Chrome Version 42.0.2311.135 (64-bit) on Mac OS 10.10.2 and 10.10.3.  I have not been actively testing with other browsers, so don't know if it's specific to Chrome. I was ignoring it for awhile, but figured that I should report it.   

Here's what appears in the console:

![screenshot_19](https://cloud.githubusercontent.com/assets/3046552/7464495/ae7e8e9a-f280-11e4-8d38-9985d6e4495e.png)

This appears after clicking or dragging in the sim. It prints out over and over, and the sim must be reloaded to make it stop.  It doesn't happen all the time, but enough to be disconcerting.

Is anyone else seeing this?

**Comment by pixelzoom** [comment]
I've seen this in multiple sims, running out of master.  hookes-law, beers-law-lab, blackbody-spectrum, scenery-phet demo, ...

**Comment by jonathanolson** [comment]
So far unable to reproduce after ~10min. Would add the following code before the erroring line, since it looks like something is passing null into something expecting Vector2:
```js
      if ( !point || ( !point.x && point.x !== 0 ) ) {
        debugger;
      }
```

Then reproduce and check the stack trace, and determine why null is being passed in.

**Comment by pixelzoom** [comment]
Added debugger breakpoint to Vector2.constains point. 

Steps to reproduce:
1. Start some sim (any one will do)
2. Start another application (I used Skype), move it to the foreground
3. Put your mouse over the browser window, and make a scrolling action (e.g. drag on a trackpad, or drag on a Magic mouse).

Here's the call stack.

![screenshot_21](https://cloud.githubusercontent.com/assets/3046552/7465354/d03a5932-f28b-11e4-87c6-ae4f4e1c669f.png)

**Comment by jonathanolson** [comment]
Can you pull Scenery and verify if this fixed all of your issues? It fixed the one I could reproduce following your instructions.

**Comment by pixelzoom** [comment]
Seems to be fixed, thanks. I'll close this issue, reopen if I encounter another scenario where it occurs.

**Comment by pixelzoom** [comment]
Reopening. I just realized that this affects published sims.  And since it requires a restart of the sim, we should probably evaluate how many sims are affected. I tested Molecules and Light 1.01, since it was most recently published, and it exhibits this issue.  I tested Acid-Base Solutions 1.1.0, and it does not exhibit this issue. 

@jonathanolson was this problem recently introduced in scenery?  Can you determine a date after which published sims will have this problem?

**Comment by jonathanolson** [comment]
Presumably broken on Feb 11th (https://github.com/phetsims/scenery/commit/da2af35c358c9809a840377dc77f4a328ba0f376).

Shouldn't this only be a problem in the console? Or does it affect the behavior of the sim (even with console closed)?

**Comment by pixelzoom** [comment]
The continuous console output seems to affect performance of the sim on desktop (Mac + Chrome). I would expect it to be even worse on iPad.

**Comment by pixelzoom** [comment]
... but that is with the console open. I haven't checked performance with the console closed.

**Comment by jonathanolson** [comment]
Can't generate a mouse-wheel event on the iPad though. Can you try testing with the console closed on desktop?

**Comment by pixelzoom** [comment]
I tested the published version of Molecules and Light, http://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_en.html.  Once this error occurs, the sim is totally unresponsive, with and without the console open.

**Comment by pixelzoom** [comment]
@ariel-phet This issue should be factored into the upcoming redeploy of sims. And sim that was published between 2/11/15 and 5/4/15 has this problem.

**Comment by jonathanolson** [comment]
I'm assigned, what task is left for this specific issue?

**Comment by pixelzoom** [comment]
I think the only thing left is to factor this into planning for sim redeployment. So I'll reassign this to @ariel-phet.

**Comment by pixelzoom** [comment]
Sounds like the plan is for all "Summer 2015" redeploys to use master common-code, so this fix will be picked up by all sims.  Closing.
