### ISSUE TITLE
Proposal to add constrainLocation to Vector2

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/dot#28]
The proposal is to add the following method to Vector2.

````
    /**
     * Constrains a location to some bounds.
     * It returns (1) the same location if the location is within the bounds
     * or (2) a location on the edge of the bounds if the location is outside the bounds
     * @param {Vector2} location
     * @param {Bounds2} bounds
     * @returns {Vector2}
     */
    constrainLocation: function( location, bounds ) {
      if ( bounds.containsCoordinates( location.x, location.y ) ) {
        return location;
      }
      else {
        var xConstrained = Math.max( Math.min( location.x, bounds.maxX ), bounds.x );
        var yConstrained = Math.max( Math.min( location.y, bounds.maxY ), bounds.y );
        return new Vector2( xConstrained, yConstrained );
      }
    };
````
It is used in MovableDragHandler to constrain the location to some dragBounds.

For a usercreatorNode where one cannot use the MovableDragHandler, then we must resort to use a SimpleDragHandler. However the SimpleDragHandler doesnt have the options of dragBounds and one is forced to copy past that method every time as seen here https://github.com/phetsims/charges-and-fields/blob/master/js/charges-and-fields/view/UserCreatorNode.js.

Apparently Bending light made such a use of this that a function was created for such a purpose 
https://github.com/phetsims/bending-light/blob/master/js/common/ConstraintBounds.js
(although it seems that they could have used MovableDragHandler instead).

**Comment by bereaphysics** [comment]
Alternatively we could incorporate this method within SimpleDragHandler since all theses instances make use of it for some dragBounds in the simpleDragHandler

**Comment by samreid** [comment]
I'm not sure of the best place to put this method (it may well be in SimpleDragHandler or Bounds2), but if we *do* end up adding it to Vector2, then I would want to choose names that make it clear whether it is creating a new vector or mutating an existing vector, and to create methods for both, with the creation variant calling the mutator variant.

**Comment by pixelzoom** [comment]
Vector2 is used for both vectors and locations.  I'm not convinced that this belongs in Vector2.

**Comment by jonathanolson** [comment]
Sounds similar to bounds2.minimumDistanceToPointSquared(), how about ```bounds2.closestPointTo( point )``` in Bounds2?

**Comment by aaronsamuel137** [comment]
We've decided to add closestPointTo to Bounds2 and not constrainLocation to Vector2. See https://github.com/phetsims/charges-and-fields/issues/39. Closing
