### ISSUE TITLE
dot contains code that is "based on Jama"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#29]
There are several files in dot that contain this documentation:

> based on Jama (http://math.nist.gov/javanumerics/jama/)

Can you elaborate on "based on"?  Are there any 3rd-party licensing issues here?

**Comment by jonathanolson** [comment]
I'd consider that dot code a derived work of Jama (as noted in emails as to what derived works we used), so it should be listed however that needs to be (sounds like it should be in the JSON).

**Comment by pixelzoom** [comment]
If it's a derived work, then you'll need to add an entry in sherpa/third-party-licenses.json.  And since dot is specified as a preload in chipper/build.json, you'll need to add the Jama entry to "licenseKeys" in build.json.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> as noted in emails as to what derived works we used

I'm not familiar with these emails. If there are other derived works that are missing from third-party-licenses.json, please add them too.

**Comment by jonathanolson** [comment]
Liberation Sans was also noted, but is already in the licensing info. I'll take care of adding the references.

**Comment by jonathanolson** [comment]
I presume I'll need the Jama version it's derived from?

**Comment by pixelzoom** [comment]
Yes.

**Comment by jonathanolson** [comment]
License URL for Jama, when it's just on the main page noted as public domain? (http://math.nist.gov/javanumerics/jama/)

Just put that url as both project/license URL?

Also, since it is not used for most simulations (and probably stripped out with require.js, but I'd need to double-check), should it be in the build.json or package.json for sims that use those parts? Probably easier to use build.json (hard to remember otherwise), but wanted to make sure.

**Comment by pixelzoom** [comment]
licenseURL is optional, used when a project has a dedicated license page.  So you can just use the "projectURL", "license" and "notes" fields. Fields are documented in the header of setThirdPartyLicenses.js.

I would put it in build.json, rather than trying to keep track of which pieces of dot a sim uses, or may call indirectly without knowing it.

**Comment by jonathanolson** [comment]
Added, let me know if there's anything else to be done.

**Comment by pixelzoom** [comment]
The "text" field needs to mention the library name and what it's general purpose. Remember, this will be massaged into a human-readable format that KP will be providing to other people.

**Comment by pixelzoom** [comment]
I'll take a stab at it...

**Comment by pixelzoom** [comment]
Modified "text" field in https://github.com/phetsims/sherpa/commit/5d65f3b8808b16aa2d7a8314f87225d316685cd2. @jonathanolson if that looks good, feel free to close.

**Comment by jonathanolson** [comment]
I thought it needed to be the license text, sorry.

**Comment by jonathanolson** [comment]
Looks great, thanks.

**Comment by pixelzoom** [comment]
I removed the long copyright string too, no need to reproduce it when it's on the website.
