### ISSUE TITLE
sphereRayIntersection appears unused, can we delete it?

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#33]
sphereRayIntersection appears unused, can we delete it?

**Comment by samreid** [comment]
Related to #31

**Comment by jonathanolson** [comment]
Seems useful for 3D atom views (was used in Molecule Shapes, may be used in Build a Molecule after changes). I'd prefer to keep it. It's code I've written from scratch (for licensing)

**Comment by samreid** [comment]
My tendency is to delete unused code and resurrect it if/when needed, still I do not know the plans for Build a Molecule and this function doesn't seem like it is doing much harm, so I'm OK to leave it.  Closing.
