### ISSUE TITLE
replace toFixed with dot.Util.toFixed?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#36]
dot uses JavaScript's built-in toFixed in Matrix3 and Matrix4. toFixed is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Should we be using dot.Util.toFixed instead?

**Comment by jonathanolson** [comment]
Same exact reasoning as https://github.com/phetsims/kite/issues/50, I'll add equivalent documentation.
