### ISSUE TITLE
Consider moving Molecule Shapes FastMath to Dot

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/dot#40]
It includes heavily optimized 3x3 matrix computations, of which the most specific to the sim is the 3x3 Singular Value Decomposition.

**Comment by jonathanolson** [comment]
Added developer-meeting label to discuss whether this code would be good to move to common code.

**Comment by pixelzoom** [comment]
9/29/15 dev meeting notes:
• @jonathanolson says this is 10x faster than numeric.js.
• Q: @samreid where else used? A: @jonathanolson inside a loop.
• relies on Float64Array, so not as general as what's currently in dot (row-major order is also different than Matrix3)
• move to dot now or when another sim needs it? @jonathanolson would like to move it now. Other developers ok with that.
• @jonathanolson will move to dot, and choose a better name (RawMatrix3?)

**Comment by jonathanolson** [comment]
Done with the name 'MatrixOps3', but still open for renaming if others have better ideas.
