### ISSUE TITLE
ObservableBounds2 is unused, can it be deleted?

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#41]
I recommend to delete, what do you think @jonathanolson?

**Comment by samreid** [comment]
Same question for ObservableMatrix3.

**Comment by samreid** [comment]
ObservableVector2 only used in Travoltage.

**Comment by jonathanolson** [comment]
I'm fine with deleting ObservableBounds2 and ObservableMatrix3. Any objections, or should I remove them?

**Comment by pixelzoom** [comment]
I've never used them, no objection to deleting.

**Comment by jonathanolson** [comment]
Removed them, particularly because ObservableMatrix3 was for some reason causing unit test errors.
