### ISSUE TITLE
Math.cosh and Math.sinh appears in complex.js

### ISSUE THREAD

**Issue by veillette** [phetsims/dot#50]
As part of the code review (see #49). There are four instances of Math.cosh and Math.sinh in Complex.js. 

Math.sinh and Math.cosh are not part of the ecmascript 5 standard. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cosh

![image](https://cloud.githubusercontent.com/assets/7633344/16150520/afc04b90-3465-11e6-8a45-1db2bd097691.png)

According to the info this would affect internet explorer user.

**Comment by samreid** [comment]
I recommend to add methods to dot/js/Util.js for cosh and sinh, and use those instead of Math.cosh and Math.sinh.

**Comment by veillette** [comment]
added cosh and sinh in DOT/Util.js. 
https://github.com/phetsims/dot/commit/1efed24bbfa72fbecaea06e853c6cf6ebaa6f106

**Comment by veillette** [comment]
I added a unit test as well.
