### ISSUE TITLE
bring documentation up to PhET standards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#52]
6/16/16 dev meeting: Decided to create this issue, as a first step towards improving knowledge sharing.

**Comment by ariel-phet** [comment]
@veillette and his team have been working on this issue. Assigning to him to comment as necessary, and reference this issue for any review issues that need to be created

**Comment by ariel-phet** [comment]
@veillette please assign back to me when work is complete or your summer work is over (which ever comes first!)

**Comment by veillette** [comment]
This issue is being tracked in #49
