### ISSUE TITLE
something got broken, is causing charges to misbehave in John Travoltage

### ISSUE THREAD

**Issue by jbphet** [phetsims/dot#53]
I was doing some work on sonification using the John Travoltage simulation, and noticed that charges were leaking out the top of JT's head (see screenshot below).  This was not a problem in the previous (fairly recent) dev release.  After some investigation, it appears to be caused by something that has changed in the dot repository.  If I check out the version of dot used in the previous dev release, which is 6d72717f9398531e4c1c14ec2765e7a700b9a120, the behavior is correct, i.e. the charges stay in JT's body.  If I check out master, the broken behavior is seen.  It looks like @andrea-phet has made several commits that could affect the functionality, assigning to her to track down and resolve.

![js-charges-leaking](https://cloud.githubusercontent.com/assets/3082831/16434827/39268844-3d4f-11e6-8799-9d35336ab772.PNG)

**Comment by veillette** [comment]
There is a subtle difference between dividedScalar instead of divideScalar.
dividedScalar returns a new Vector4 whereas divideScalar mutates the vector.

Before the fix, https://github.com/phetsims/dot/commit/6d72717f9398531e4c1c14ec2765e7a700b9a120, it used to retrun a new Vector4

**Comment by veillette** [comment]
And I think I am the one who did the faulty commit.

**Comment by samreid** [comment]
I doubt John Travoltage is using Vector4. @veillette please fix the issue you identified and I'll proceed to bisect to identify the John Travoltage problem.

**Comment by andrea-phet** [comment]
If I checkout https://github.com/phetsims/dot/commit/eb73a3c4c4b8353eef56fdab30aadf04ea1fa069 the behavior is correct, but if I checkout the next commit, https://github.com/phetsims/dot/commit/eec2a2dc0f23af51e3d910b817dcfab2c963a18b, the broken behavior is seen. So I think something is happening in the new lineSegmentIntersection algorithm.

**Comment by samreid** [comment]
dot 455447cedc0b42bc5c1bbb38b37b7c92cc7e9e8c is good
dot d578b9cbed558fcc502a59a3884bed3cf68505ca is bad
dot 6448a04cc1a1dfa782315d3ad3bafa1346ac2c4b is bad
dot eb73a3c4c4b8353eef56fdab30aadf04ea1fa069 is good 
dot eec2a2dc0f23af51e3d910b817dcfab2c963a18b is bad, so this is the commit that introduced the issue.  Note: it is possible John Travoltage was relying on buggy dot behavior, but we should check it out.

**Comment by samreid** [comment]
I'll move @veillette's Vector4 comment to a new issue, since it seems irrelevant to this John Travoltage behavior.

**Comment by samreid** [comment]
I see the following other sims that use lineSegmentIntersection:
* energy-skate-park-basics
* optics-lab
* sugar-and-salt-solutions

as well as StarShape, which is used in many games.

**Comment by andrea-phet** [comment]
The above commit replaces 0 with epsilon when testing whether an intersection exists on the line segments. It fixes the problematic behavior in John Travoltage. If needed, however, it may be more robust to write an algorithm that doesn't use epsilon.

**Comment by samreid** [comment]
Is John Travoltage relying on incorrect results to a segment-segment intersection, or perhaps needs a custom (segment-segment nearly intersect) algorithm?

**Comment by andrea-phet** [comment]
@samreid I think there are incorrect results from the segment segment intersection. I tried using the previous algorithm taken from paul bourke, and that fixes the problematic behavior in John Travoltage, without having to check for "nearly intersection."

**Comment by andrea-phet** [comment]
The current commit on master fixes the John Travoltage issue, assigning to @jbphet to test. I'll make a separate issue for this nearly intersection problem.

**Comment by jbphet** [comment]
I verified that charges behave correctly in John Travoltage now, closing.
