### ISSUE TITLE
Return values from Vector4 may have been disturbed

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#54]
In #53 @veillette said:

There is a subtle difference between dividedScalar and divideScalar.
dividedScalar returns a new Vector4 whereas divideScalar mutates the vector.
Before the fix, 6d72717, it used to return a new Vector4
And I think I am the one who did the faulty commit.

**Comment by veillette** [comment]
This was addressed in https://github.com/phetsims/dot/commit/d2bc7ad84d37b5adcc50efd7879eecfaa616a205

**Comment by veillette** [comment]
In addition, I checked that the normalized methods in Vector2, Vector3 were correct.

**Comment by veillette** [comment]
I found that Vector4 is not used in any of our sims.:(.  
In any case, I'm glad we caught this bug. Closing
