### ISSUE TITLE
document Random.sample

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#59]
Currently:

```js
    // For lodash interoperability, but with seeded random
    sample: function( array ) {
```

If I'm new to this, then:

(1) I need to guess which lodash functionality this is interoperable with.  That may be simple, unless I've already had to deal with `randomIntegerBetween`, whose name has no correspondence to lodash `_.random`.  So why not just say "This is a replacement for lodash _.sample" ?

(2) Then I need to go find the documentation for lodash `sample`. That makes me unhappy, because it wastes my time.

So please, let's give this function proper documentation (as should be the case with all common code).

**Comment by samreid** [comment]
Random.sample should have proper documentation by now, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
👍 Closing.
