### ISSUE TITLE
Random.nextGaussian should be seedable

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#60]
In order to support replicable playback for phet-io, we would like replicable random number support in Random.  Random.nextGaussian currently relies on Math.random, so is unseeded.

**Comment by samreid** [comment]
Fixed above.  The only use case is in States of Matter.  I tested it manually and with a fuzz test and did not see any issues, but it would still be nice if @jbphet could review and make sure everything is OK after this change.

**Comment by jbphet** [comment]
The changes look reasonable and the sim's behavior seems correct.  Closing.

**Comment by pixelzoom** [comment]
Reopening. The documentation still says:

```js
179 * This random number is not seeded
```

**Comment by samreid** [comment]
I fixed the docs in the preceding commit.  @pixelzoom please double check and close if all is well.

**Comment by pixelzoom** [comment]
👍 Closing.
