### ISSUE TITLE
Util.isInteger should throw an assertion error if a non-number is passed in.

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#61]
Util.isInteger is currently defined like so:

``` js
    /**
     * Returns whether the input is a number that is an integer (no fractional part).
     * @public
     *
     * @param {number} n
     * @returns {boolean}
     */
    isInteger: function( n ) {
      return ( typeof n === 'number' ) && ( n % 1 === 0 );
    }
```

In the doc, the parameter type is described as `{number}` and indeed it would seem like passing string, objects or booleans to this function should flagged as a logic error.  Hence, we should change `typeof number` to be an assert.  I discussed this with @pixelzoom and he agreed we should move to the assert.  I should also run fuzz test after this change to see if anything was relying on passing in non-numbers.

**Comment by samreid** [comment]
After making this change, I ran http://localhost/chipper/test-server/test-sims.html?loadOnly and all is well.  Committing.

**Comment by samreid** [comment]
Committed above, @pixelzoom would you mind double checking the change?

**Comment by pixelzoom** [comment]
Looks good. But when an assertion fails, I like to have the offending value in the assertion message, like so:

```js
assert && assert( typeof n === 'number', 'isInteger requires its argument to be a number: ' + n );
```

@samreid Look OK?

**Comment by samreid** [comment]
Yes, that is a good plan, closing.

**Comment by samreid** [comment]
That looks preferable, thanks!  Also, please be apprised of https://github.com/phetsims/tasks/issues/1039 in which we may use `Number.isInteger` instead of `% 1 === 0`

**Comment by pixelzoom** [comment]
Changed in the above commit. 

Thanks for the heads up on phetsims/tasks#1039.  I'm going to ignore that for the purposes of this issues. 

Closing.
