### ISSUE TITLE
Code review for Random.js

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#63]
Since Random.js will be more widely used (via phet.joist.random), it should be reviewed.  @samreid should prepare it for review, then it would be nice if @pixelzoom has time to take a closer look.

**Comment by samreid** [comment]
I've finished my cleanup, @pixelzoom are you available to review Random.js?

**Comment by pixelzoom** [comment]
Cleanup looks great.

There is an unrelated issue, probably introduced when `shuffle` was implemented.  IDEA is flagging this line as a potential issue, "Constructor called without new"

```js
133 var result = Array( array.length );
```

**Comment by samreid** [comment]
Agreed, we should use `new Array`, fixed above and it looks good in testing.  Anything else here?

**Comment by pixelzoom** [comment]
Nothing else, closing.
