### ISSUE TITLE
Review RunningAverage

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#69]
Moved here during https://github.com/phetsims/circuit-construction-kit-common/issues/317

@jonathanolson can you make sure it's good to go?

**Comment by pixelzoom** [comment]
This has been "ready for review" since 8/2017, raising priority.

**Comment by samreid** [comment]
This implementation looks heavily micro-optimized and overly complicated and hence error-prone.  I recommend a rewrite that focuses on clarity and correctness.

**Comment by jonathanolson** [comment]
This looks correct to me. It looks optimized (not micro-optimized) to me, and I'd like to keep it as-is. Objections @samreid?

**Comment by samreid** [comment]
Without unit tests, I think the existing implementation is too complex to leave as-is.  Here is an untested simplified version that creates more garbage:

<details>
```js
// Copyright 2017-2020, University of Colorado Boulder

/**
 * Data structure that keeps track of running average over a given window.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Jonathan Olson (PhET Interactive Simulations)
 */

import dot from './dot.js';

class RunningAverage {
  /**
   * @param {number} windowSize - number of points to average
   */
  constructor( windowSize ) {

    assert && assert( windowSize > 0, 'window size must be positive' );

    // @private {number}
    this.windowSize = windowSize;

    // @private {number[]} - Used circularly.
    this.samples = [];

    this.clear();
  }


  /**
   * Clear the running average.
   * @public
   */
  clear() {
    this.samples.length = 0;
  }

  /**
   * Gets the current value of the running average.
   * @public
   *
   * @returns {number}
   */
  getRunningAverage() {
    return _.sum( this.samples ) / this.samples.length;
  }

  /**
   * Returns whether the number of samples is at least as large as the window size (the buffer is full).
   * @public
   *
   * @returns {boolean}
   */
  isSaturated() {
    return this.samples.length >= this.windowSize;
  }

  /**
   * Add a data point to the average and return the new running average.
   * @public
   *
   * @param {number} sample
   * @returns {number}
   */
  updateRunningAverage( sample ) {
    assert && assert( typeof sample === 'number' && isFinite( sample ) );
    this.samples.push( sample );

    while ( this.samples.length > this.windowSize ) {
      this.samples.shift();
    }

    return this.getRunningAverage();
  }
}

dot.register( 'RunningAverage', RunningAverage );

export default RunningAverage;
```
</details>

Leaving self-assigned to consider unit tests or performance comparison.

**Comment by jonathanolson** [comment]
That implementation is potentially thousands of times slower for the anticipated usages, and seems to remove the point of the file. Agreed it's simpler, but if you have 10,000 samples, you're going from an effectively constant-time operation to moving every single of the 10,000 items in memory (the shift) PLUS re-scanning all 10,000 of the items. I wouldn't want tools used in measuring performance (e.g. average fps over longer durations) to be significantly affecting said performance.

Maybe it would make sense to have that version ALSO, and use it for unit tests? Also, the documentation of that should not state that the array is used circularly, as it is not.

**Comment by samreid** [comment]
I'm feeling more confident about RunningAverage after adding some basic unit tests, I think this can be closed.
