### ISSUE TITLE
Matrix.affine and Matrix.setToAffine have different argument orderings

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#71]
Matrix3.js:69 shows the argument order remapping:

```js
Matrix3.affine = function( m00, m10, m01, m11, m02, m12 ) { return Matrix3.dirtyFromPool().setToAffine( m00, m01, m02, m10, m11, m12 ); };
```

From the scenery playground:

```js
var shear1 = dot.Matrix3.dirtyFromPool().setToAffine( 1, 0.5, 0, 0, 1, 0 );
var shear2 = dot.Matrix3.affine( 1, 0.5, 0, 0, 1, 0 );

undefined
shear1.entries
Float64Array(9) [1, 0, 0, 0.5, 1, 0, 0, 0, 1]
shear2.entries
Float64Array(9) [1, 0.5, 0, 0, 0, 0, 1, 0, 1]
```

Is this arg reordering intentional?

**Comment by jonathanolson** [comment]
It was, interestingly enough, potentially intentional (SVG matrices use that order for input). I'm up for making things consistent. What do you think should be done?

**Comment by samreid** [comment]
I prefer making them consistent, and was expecting m00, m01, ... ordering (not sure if that violates any other conventions).

**Comment by jonathanolson** [comment]
Patched, can you verify?

**Comment by samreid** [comment]
Dot looks good, and I I updated the 2 occurrences in Wave Interference.  I'll check phetcommon later.

**Comment by samreid** [comment]
I checked the occurrences in phetcommon, here are my notes:

```
abcdef => acebdf
scale,0,0,scale,offset.x,offset.y
scale,0,offset.x,0,scale,offset.y

xscale,0,0,yscale,offset.x,offset.y
xscale,0,offset.x,0,yscale,offset.y

m00,0,0,m11,m02,m12
m00,0,m02,0,m11,m12

m00,0,0,m11,m02,m12
m00,0,m02,0,m11,m12
```

All is well, closing.
