### ISSUE TITLE
Add median to dot.Util

### ISSUE THREAD

**Issue by zepumph** [phetsims/dot#72]
needed to support interaction dashboard https://github.com/phetsims/interaction-dashboard/issues/59. I think it is better to pull this into common code than in a common dir in that sim repo.

**Comment by zepumph** [comment]
@samreid please spotcheck.

**Comment by jonathanolson** [comment]
Saw the issue, some brief comments:

- Things like `something.forEach( function( ... ) { assert && assert( ... ); } )` should generally not be kept or run if we have assertions disabled. Prefer rewriting to `assert && something.forEach( function( ... ) { assert( ... ); } )`
- If an array has length zero, then it has no median, right? So we might want to use null (our standard value for "there isn't a thing like that")
- I didn't realize that the median for odd-length arrays would be the mean of the middlemost two elements. If we're supporting non-numbers, then we'll need to pass in an average() function also? Maybe we only support median of numbers, and get rid of the getMedianFromSortedArray? Sorry about that.
- `sortedArray instanceof Array` we decided to use `Array.isArray( sortedArray )`

**Comment by samreid** [comment]
> I didn't realize that the median for odd-length arrays would be the mean of the middlemost two elements.

I think you mean even-length arrays.  Also, I didn't realize that either, but according to wikipedia and other sources it is correct: https://en.wikipedia.org/wiki/Median

**Comment by zepumph** [comment]
>I didn't realize that the median for odd-length arrays would be the mean of the middlemost two elements. If we're supporting non-numbers, then we'll need to pass in an average() function also? Maybe we only support median of numbers, and get rid of the getMedianFromSortedArray? Sorry about that.

I decided against supporting non numbers, so I got rid of the multi function solution. Everything else was fixed as expected. Back to you for a spot check @jonathanolson.

**Comment by jonathanolson** [comment]
Looks good, thanks! Added `@public` and converted `2.0` => `2`, closing.
