### ISSUE TITLE
built-in modulo operator % is broken on iOS 9 + Safari 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#75]
The built-in modulo operator `%` is broken on mobile Safari in iOS9.  See for example https://github.com/phetsims/equality-explorer/issues/134#issuecomment-403556496, where we discovered:

```
> 1e9 % 1e9
0
> 1e10 % 1e10
2.65249474e-315
```
 
After discussing with @jonathanolson, we are going to:

- [x] Create `Util.mod` as a replacement for `%`

- [x] Use `Util.mod` in `Util.gcd`, since it is responsible for https://github.com/phetsims/equality-explorer/issues/134.

- [ ] Discuss what other uses of `%` to replace with `Util.mod`.

**Comment by pixelzoom** [comment]
@jonathanolson I implemented `Util.mod` and patched `Util.gcd`.  Please review the above commit.

**Comment by jonathanolson** [comment]
Commit above looks good, thanks!

**Comment by pixelzoom** [comment]
We should add unit test for `Util.mod` to `UtilTests.js`, but I'm not clear on what a sufficient set of tests would be.

**Comment by pixelzoom** [comment]
This is labeled for developer meeting to (1) make all developers aware of this problem, and (2) discuss what other uses of `%` to replace with `Util.mod`.

**Comment by samreid** [comment]
* We have hopefully caught problems in QA, so this reduces the likelihood of a problem like this in the wild.  We could rely on QA going forward.

If we are still worried, we could:
* temporarily "transpile" all `%` to `Util.modAssert` which tests the arguments to see if they are in a valid range (which we determine from iOS testing).
* manually review code existing or new code

**Comment by pixelzoom** [comment]
7/12/18 dev meeting
• made all developers aware
• no proactive changes, fix things as we find them
