### ISSUE TITLE
Vector sets all undefined values to 0

### ISSUE THREAD

**Issue by chrisklus** [phetsims/dot#85]
@samreid and I noticed that in Vector2, Vector3, and Vector4, if a value is not provided, then it defaults that value to 0. This is fine and expected for something like `new Vector2(); // (0, 0)`, but is buggy and not desirable for something like `new Vector2( 7 ) // (7, 0)` or  `new Vector2( undefined, 7 ) // (0, 7)`. We think that only either no arguments or all arguments being typeof number would be better constraints.

**Comment by samreid** [comment]
Also, @jonathanolson pointed out that it is important for this code to be well-optimized.  For example, I counted:

181,235 Vector2 created during startup of EFAC
517,348 Vector2 created during startup of Wave Interference

**Comment by samreid** [comment]
@jonathanolson would it be OK if we streamline the Vector2 constructor by requiring that it have 2 arguments, and create a separate method for creating a new zero Vector2?

**Comment by samreid** [comment]
In my working copy, I converted all `new Vector2()` to `new Vector2(0,0)`.  Same for `new dot.Vector2()`.  During wave interference startup, this avoids over a million undefined checks.  Also, the Vector2 constructor is a bit simpler, so that's nice.  Also, it seems to me that `new Vector2(0,0)` is just as readable as `new Vector2()`, so I'm a fan of this approach.  I'll hold off committing until hearing from @jonathanolson.

**Comment by jonathanolson** [comment]
It seems fine to me, as long as there is a clear assertion stating what the change was.

**Comment by samreid** [comment]
I fixed and pushed this for Vector2.  This change revealed a problem in Balloons and Static Electricity unit tests, I'll create a separate issue for that.

**Comment by samreid** [comment]
I committed the proposed changes.  @chrisklus can you please take a look around and see if I've forgotten anything?

**Comment by pixelzoom** [comment]
CT is showing Uncaught Errors in several sims, related to Vector2 and Vector3.  The messages are “x needs to be a number” and “z needs to be a number”.   Affected sims are capacitor-lab-basics, estimation, gene-expression-essentials, molecule-shapes, molecule-shapes-basics, projectile-motion.  I'm guessing that these problems are related to this issue.

**Comment by samreid** [comment]
I pushed proposed fixes for several of the repos.

**Comment by jonathanolson** [comment]
Looks great to me, thanks!
