### ISSUE TITLE
rename set methods

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#9]
In order to avoid collisions with Property.set, the dot "set" methods like Vector2.set, Bounds2.set, etc. should be renamed.

We should have 
Vector2.set=>setXY
Vector3.set=>setXYZ
Vector4.set=>setXYZ
Quaternion.set=>setXYZW
Bounds2.set=>setMinMax
Transform.set=>setMatrix

**Comment by pixelzoom** [comment]
Looks like this was done >1.5 years ago, but no request was made to review. Since it hasn't resulted in problems, I'll close this issue.
