### ISSUE TITLE
Bounds2.dirtyFromPool() doesn't work

### ISSUE THREAD

**Issue by jbphet** [phetsims/dot#91]
@chrisklus and I were working to reduce allocations in Energy Forms and Changes, and we tried to use `Bounds2.dirtyFromPool`, and it threw an assertion.  I suspect that all that is needed is a no-argument constructor, but there may be a reason that this doesn't exist, so I'm logging an issue and assigning to @jonathanolson, since he created both `Bounds2` and `Poolable`.

**Comment by chrisklus** [comment]
@jbphet and I noticed that Vector2's poolable mixInto() call has default values, but Bounds2 did not. We added those and now `Bounds2.dirtyFromPool` works.

@jonathanolson please review.

**Comment by samreid** [comment]
The above commit uses these default values for Bounds2:

```js
[ Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY, Number.NEGATIVE_INFINITY, Number.NEGATIVE_INFINITY ]
```

It is unclear why these are desirable/correct defaults.  Can you please document/clarify?

**Comment by chrisklus** [comment]
We were using `Bounds2.dirtyFromPool` as a replacement of allocating new Bounds as `Bounds2.NOTHING`, which contains those values. 

Do you think `[ 0, 0, 0, 0 ]` would be more appropriate?

**Comment by samreid** [comment]
> We were using `Bounds2.dirtyFromPool` as a replacement for allocating new Bounds as `Bounds2.NOTHING`, which contains those values. 

Bounds2.NOTHING seems reasonable, perhaps document it and use its values like:
```
defaultArguments: [ Bounds2.NOTHING.minX, etc...]
```

**Comment by chrisklus** [comment]
Fixed, thanks @samreid.

**Comment by jonathanolson** [comment]
This looks great to me, thanks!
