### ISSUE TITLE
Unnecessary `new Matrix` in one unused method.

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#93]
While working on https://github.com/phetsims/wave-interference/issues/354 I noticed this in Matrix.js:

```js
    plusEquals: function( matrix ) {
      this.checkMatrixDimensions( matrix );
      var result = new Matrix( this.m, this.n );
      for ( var i = 0; i < this.m; i++ ) {
        for ( var j = 0; j < this.n; j++ ) {
          var index = result.index( i, j );
          this.entries[ index ] = this.entries[ index ] + matrix.entries[ index ];
        }
      }
      return this;
    },
```

Note the allocation of `var result = new Matrix( this.m, this.n );` is unnecessary and we can use `this.index` instead of `result.index`.  However, I noticed that our code doesn't ever call `plusEquals` so this isn't causing any problems at the moment.

**Comment by jonathanolson** [comment]
Looks good, thanks!
