### ISSUE TITLE
Improve Transform3 matrix validation

### ISSUE THREAD

**Issue by samreid** [phetsims/dot#98]
While working on https://github.com/phetsims/circuit-construction-kit-common/issues/536 and https://github.com/phetsims/circuit-construction-kit-common/issues/535, I noticed that Transform3 uses a rule for validating its matrices that is incompatible with the strategy used in ModelViewTransform2.  It would be nice to use an approach that can be overriden in ModelViewTransform2.  I'll commit then reassign to @jonathanolson for review.

**Comment by samreid** [comment]
Fixed in the preceding commits. Also, I remove an extraneous assertion in `setMatrix` since it immediately calls `invalidate` with the same value.

@jonathanolson do you mind double checking?  It should be quick.

**Comment by jonathanolson** [comment]
That looks nice to me, thanks!
